### ISSUE TITLE
Project menu: Clicking "Project" does not open menu

### ISSUE THREAD

**Issue by rbdannenberg** [rbdannenberg/soundcool#66] opened 2020-05-18 22:44 UTC
You have to click just to the left of the word Project to open the Project menu.

**Comment by ankit204** [comment] 2020-05-23 04:07
The project drop down menu doesn't work by clicking the text or the icon. Priority++.

**Comment by im-Amitto** [comment] 2020-05-23 04:10
I can take care of that

**Comment by ankit204** [comment] 2020-05-23 04:20
Am I right that all drop down menus have stopped working? For example try SignalGen: I cannot get wave type and modulation drop downs to work.

**Comment by im-Amitto** [comment] 2020-05-23 04:34
This issue occurred because "Project" is written outside the dropdown element
Fixed

**Comment by im-Amitto** [comment] 2020-05-23 07:08
@ankit204 Dropdown is working fine. Most probably your browser configuration is messed up. Try testing in incognito-mode. if it does not work in incognito-mode then please share your browser details.

**Comment by ankit204** [comment] 2020-05-25 00:56
I don't even know what "Most probably your browser configuration is messed up" means. Please explain.
I tried it in Chrome incognito mode but, that didn't help either. 

Browsers I tested and it doesn't work on:
Chrome: 81.0.4044.138
Firefox: 76.0.1 
Firefox (nightly): 76.0a1 (2020-03-17)

**Comment by im-Amitto** [comment] 2020-05-25 01:16
@ankit204 Sometime an added extension can mess things up but if it's not working in incognito then it's not a configuration issue. It's super weird that no dropdown is working for you.
I will test a fresh copy of soundcool and share a binary with you ASAP so we can know for sure that is it a code related issue or platform-specific issue.

**Comment by ankit204** [comment] 2020-05-26 20:52
@im-Amitto, I can confirm that dropdown menu works with a fresh clone and installing dependencies. We can say that the issue I was facing had to do with my local setup. Closing it.

**Closed as completed by ankit204** 2020-05-26 20:52 UTC
Labels: bug, frontend, Priority Critical
