### ISSUE TITLE
Login does not work.

### ISSUE THREAD

**Issue by rbdannenberg** [rbdannenberg/soundcool#27] opened 2020-03-04 13:05 UTC
When I log in as user1@welcome.com, a "Session expired" message appears. The interface displays a "Logout" button, but when I try to open a sound, I get a message to login first.

**Comment by im-Amitto** [comment] 2020-03-04 13:49
@rbdannenberg I'm not able to reproduce the error, can you please receord a video or share terminal logs.

**Comment by ankit204** [comment] 2020-03-04 14:43
Logging in worked after some debugging. Closing it.

**Closed as completed by ankit204** 2020-03-04 14:43 UTC
