### ISSUE TITLE
"Register to save" button doesn't work when running sever using binary

### ISSUE THREAD

**Issue by ankit204** [rbdannenberg/soundcool#54] opened 2020-05-05 02:57 UTC
Steps:
1. Click on Create Project
2. Edit the project
3. Click on Register to save button

Registering in the pop-up dialog doesn't work.

**Comment by im-Amitto** [comment] 2020-05-05 04:15
@ankit204 I'm not able to reproduce the error. Let me know if anyone else can?
cc: @Kristin33 @rbdannenberg @ameykpatel

**Comment by im-Amitto** [comment] 2020-05-15 03:40
Closing the issue

**Closed as completed by im-Amitto** 2020-05-15 03:40 UTC
Labels: sqlite
