### ISSUE TITLE
Saving the webaudio object

### ISSUE THREAD

**Issue by anusfoil** [rbdannenberg/soundcool#18] opened 2019-08-08 23:54 UTC
What happens behind saving is that we copy all the redux state which contains a list of modules, each module is an object with different fields (delayTime in delay module, frequency in signal generator module, things like that.) However, each module is also carrying an webaudio object (ScSpeaker, ScSignalGen, as defined in `/src/audio`) and that creates problems when saving. The following error shows up after you connect two modules in the project editor, and then try to save it.

<img width="724" alt="WX20190808-193641@2x" src="https://user-images.githubusercontent.com/31784445/62744706-cb55fb00-ba15-11e9-9dd2-4ee1f58b68ad.png">

We need to implement a way to exclude the webaudio objects when saving, and also reinitialize webaudio objects when we load a project. 

[from RBD] My take on this is there must be some redux state that's easily converted to JSON by calling some standard function -- this would be the easy way, but not surprisingly the simple easy approach doesn't work, as the error message shows. The solution is to _define_  a format for project state. This is not just JSON for some bunch of Redux state, this is JSON with a defined set of attributes, types, and values needed to save and restore a project. There will of course have to be special code to extract state to be saved and special code to reconstruct objects from saved state information. This slightly tricky because a collection of modules in a project is linked in a graph structure, so typically that means using transitive closure to locate all the modules (or since we display them, there is probably a simple display list), giving each module a unique name or number, and representing links/connections between modules in terms of these names. Reconstructing means instantiating all the modules, then linking them according to the saved connections (however they are represented).

**Comment by ankit204** [comment] 2020-08-11 19:08
Potential duplicate of https://github.com/rbdannenberg/soundcool/issues/23. Closing it.

**Closed as completed by ankit204** 2020-08-11 19:08 UTC
Labels: WebAudio, frontend
